width = 400
samples = 100
depth = 50

[camera]
focal_length = 10.0
aperture = 0.0
vertical_fov = 80.0
aspect_ratio = 1.0

[camera.origin]
x = 0.0
y = 0.0
z = 9.0

[camera.lower_left_corner]
x = -8.390995979309082
y = -8.390995979309082
z = -1.0

[camera.horizontal]
x = 16.781991958618164
y = 0.0
z = 0.0

[camera.vertical]
x = 0.0
y = 16.781991958618164
z = 0.0

[camera.up]
x = 0.0
y = 1.0
z = 0.0

[camera.u]
x = 1.0
y = 0.0
z = 0.0

[camera.v]
x = 0.0
y = 1.0
z = 0.0

[camera.w]
x = 0.0
y = 0.0
z = 1.0

[[scene.objects]]
renderable = "Skybox"

[scene.objects.top_color]
x = 0.5
y = 0.699999988079071
z = 1.0

[scene.objects.bottom_color]
x = 1.0
y = 1.0
z = 1.0

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Quad"

[scene.objects.hittable.q]
x = -3.0
y = -2.0
z = 5.0

[scene.objects.hittable.u]
x = 0.0
y = 0.0
z = -4.0

[scene.objects.hittable.v]
x = 0.0
y = 4.0
z = 0.0

[scene.objects.hittable.w]
x = 1.0
y = -0.0
z = 0.0

[scene.objects.sampleable]
sampleable = "Lambertian"

[scene.objects.sampleable.texture]
texturable = "ColorTexture"

[scene.objects.sampleable.texture.albedo]
x = 1.0
y = 0.20000000298023224
z = 0.20000000298023224

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Quad"

[scene.objects.hittable.q]
x = -2.0
y = -2.0
z = 0.0

[scene.objects.hittable.u]
x = 4.0
y = 0.0
z = 0.0

[scene.objects.hittable.v]
x = 0.0
y = 4.0
z = 0.0

[scene.objects.hittable.w]
x = 0.0
y = 0.0
z = 1.0

[scene.objects.sampleable]
sampleable = "Lambertian"

[scene.objects.sampleable.texture]
texturable = "ColorTexture"

[scene.objects.sampleable.texture.albedo]
x = 0.20000000298023224
y = 1.0
z = 0.20000000298023224

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Quad"

[scene.objects.hittable.q]
x = 3.0
y = -2.0
z = 1.0

[scene.objects.hittable.u]
x = 0.0
y = 0.0
z = 4.0

[scene.objects.hittable.v]
x = 0.0
y = 4.0
z = 0.0

[scene.objects.hittable.w]
x = -1.0
y = 0.0
z = 0.0

[scene.objects.sampleable]
sampleable = "Lambertian"

[scene.objects.sampleable.texture]
texturable = "ColorTexture"

[scene.objects.sampleable.texture.albedo]
x = 0.20000000298023224
y = 0.20000000298023224
z = 1.0

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Quad"

[scene.objects.hittable.q]
x = -2.0
y = 3.0
z = 1.0

[scene.objects.hittable.u]
x = 4.0
y = 0.0
z = 0.0

[scene.objects.hittable.v]
x = 0.0
y = 0.0
z = 4.0

[scene.objects.hittable.w]
x = 0.0
y = -1.0
z = 0.0

[scene.objects.sampleable]
sampleable = "Lambertian"

[scene.objects.sampleable.texture]
texturable = "ColorTexture"

[scene.objects.sampleable.texture.albedo]
x = 1.0
y = 0.5
z = 0.0

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Quad"

[scene.objects.hittable.q]
x = -2.0
y = -3.0
z = 5.0

[scene.objects.hittable.u]
x = 4.0
y = 0.0
z = 0.0

[scene.objects.hittable.v]
x = 0.0
y = 0.0
z = -4.0

[scene.objects.hittable.w]
x = -0.0
y = 1.0
z = 0.0

[scene.objects.sampleable]
sampleable = "Lambertian"

[scene.objects.sampleable.texture]
texturable = "ColorTexture"

[scene.objects.sampleable.texture.albedo]
x = 0.20000000298023224
y = 0.800000011920929
z = 0.800000011920929
