width = 400
samples = 100
depth = 50

[camera]
focal_length = 10.0
aperture = 0.0
vertical_fov = 20.0
aspect_ratio = 1.7777777910232544

[camera.origin]
x = 26.0
y = 3.0
z = 6.0

[camera.lower_left_corner]
x = 15.622400283813477
y = 0.8634642958641052
z = 6.822257041931152

[camera.horizontal]
x = 1.409735083580017
y = 0.0
z = -6.108851909637451

[camera.vertical]
x = -0.128687784075737
y = 3.5240654945373535
z = -0.029697183519601822

[camera.up]
x = 0.0
y = 1.0
z = 0.0

[camera.u]
x = 0.22485950589179993
y = 0.0
z = -0.9743912220001221

[camera.v]
x = -0.036491237580776215
y = 0.9992984533309937
z = -0.008421055041253567

[camera.w]
x = 0.9737076163291931
y = 0.03745029494166374
z = 0.22470176219940186

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Sphere"
radius = 1000.0

[scene.objects.hittable.center]
time = 0.0

[scene.objects.hittable.center.origin]
x = 0.0
y = -1000.0
z = 0.0

[scene.objects.hittable.center.direction]
x = 0.0
y = 0.0
z = 0.0

[scene.objects.sampleable]
sampleable = "Lambertian"

[scene.objects.sampleable.texture]
texturable = "NoiseTexture"
scale = 0.10000000149011612

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Sphere"
radius = 2.0

[scene.objects.hittable.center]
time = 0.0

[scene.objects.hittable.center.origin]
x = 0.0
y = 2.0
z = 0.0

[scene.objects.hittable.center.direction]
x = 0.0
y = 0.0
z = 0.0

[scene.objects.sampleable]
sampleable = "Lambertian"

[scene.objects.sampleable.texture]
texturable = "NoiseTexture"
scale = 4.0

[[scene.objects]]
renderable = "RenderableImpl"

[scene.objects.hittable]
hittable = "Quad"

[scene.objects.hittable.q]
x = 3.0
y = 1.0
z = -2.0

[scene.objects.hittable.u]
x = 2.0
y = 0.0
z = 0.0

[scene.objects.hittable.v]
x = 0.0
y = 2.0
z = 0.0

[scene.objects.hittable.w]
x = 0.0
y = 0.0
z = 1.0

[scene.objects.sampleable]
sampleable = "DiffuseLight"

[scene.objects.sampleable.texture]
texturable = "ColorTexture"

[scene.objects.sampleable.texture.albedo]
x = 4.0
y = 4.0
z = 4.0
