[package]
name = "rustray"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
rand = "0.9.2"
hdrhistogram = "7.5.4"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8.19"
typetag = "0.2.21"
